### ISSUE TITLE
[Feature request] websocket support

### ISSUE THREAD

**Issue by liho00** [farzinadil/Dogefather#1]
Hi, its a great program, but i am curious why dont you use websocket instead of rest api call? Because Websocket is much more faster and only push message when there is an updates, while rest api calls are quite slow and consumes more resources.

**Comment by farzinadil** [comment]
Hi, you are right WebSocket will be better. I will look over the filtered stream from the Twitter API (https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/quick-start) and see if I can get it to work.

**Comment by farzinadil** [comment]
It uses filtered stream from Twitter now.
