### ISSUE TITLE
Video Tutorial

### ISSUE THREAD

**Issue by Keeksters** [farzinadil/Dogefather#3]
Hi I set up the bot based on the instructions given in the readme file but am getting a 403 "something went wrong" error, repeatedly upon running it. Would you be able to post a video of setting up the bot, following the instructions step by step?

**Comment by Keeksters** [comment]
In particular, I seem to be having problems with these 2 parts of the code:

      response = requests.request("GET", url, headers=headers, params=params)
          print(response.status_code)

This section, located in the connect_to_input function, looks like it's supposed to return the number 200, but only returns the number "403" over and over.

        except:
            print("Something went wrong")

This line, located at the end of the "main" function, seems to execute due to some error, and I can only assume that error is due to the previous thing returning 403 instead of 200.

If you know the issue here I would love to hear it, but I think a comprehensive video tutorial about getting the bot set up and running it would be very beneficial. Thanks.

**Comment by farzinadil** [comment]
Hi, sure I can make a video right now. In the meantime, I think you can try to change the except print statements to print the exception like `except Exception as e: print(e)`. It seems like one of the requests you are making is not working. You can try to requests individually in Postman or try running just the Twitter User-Tweet-Timeline code: https://github.com/twitterdev/Twitter-API-v2-sample-code/blob/master/User-Tweet-Timeline/user_tweets.py

**Comment by farzinadil** [comment]
https://youtu.be/RjpdukFzP9s . Here's the tutorial on how to set it up. I did this on a different computer just to make sure.
